name: Chapter 3.6 - IF and Job Status Functions
on: [push, pull_request]

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Functions
        run: |
          echo ${{ contains( 'hello', 'll' ) }}
          echo ${{ startsWith( 'hello', 'he' ) }}
          echo ${{ endsWith( 'hello', 'lo' ) }}
          echo ${{ format('Hello {0} {1} {2}', 'World', '!', '!') }}
  conditional:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Failed Step
        run: eccho "$GITHUB_CONTEXT"
      - name: Even with Failure Run Step
        if: failure()
        run: echo "$GITHUB_CONTEXT"
      - name: Always Run Step
        if: always()
        run: echo "$GITHUB_CONTEXT"
